### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by CrazyFireDog** [ThomasCassimon/Chezz#75]
When performing an undo at the beginning of the game (no moves have been done or you did undo until start of the game) the board flips around and some pieces may disappear.

**Comment by CrazyFireDog** [comment]
gives exception if undo done at start of game

**Comment by ThomasCassimon** [comment]
Fixed in upcoming commit, getLastMove() now returns a move if there is a 'last move' or null if there isn't a 'last move'. You can check if there's a 'last move' beforehand using hasLastMove(). This returns a boolean indicating wheter or not the gameManager has a move in its history
